window.GAMES = [

// … ajoute tous tes jeux (url ou null si “coming soon”)
  
      { title: 'Fallout 3', url: 'games/fallout-3.html' },
      { title: 'Fallout : New Vegas', url: 'games/fallout-new-vegas.html' },
      { title: 'Dark Souls II', url: 'games/dark-souls-ii.html' },
      { title: 'Elden Ring', url: 'games/elden-ring.html' },
      { title: 'Lords of the Fallen (2014)', url: 'games/lords-of-the-fallen-2014.html' },
      { title: 'Lies of P', url: 'games/lies-of-p.html' },
      { title: 'Batman : Arkham Asylum', url: 'games/batman-arkham-asylum.html' },
      { title: 'Batman : Arkham Knight', url: 'games/batman-arkham-knight.html' },
      { title: 'Hogwarts Legacy', url: 'games/hogwarts-legacy.html' },
      { title: 'Lego Harry Potter : Années 1 à 4', url: 'games/lego-harry-potter-annees-1-a-4.html' },
      { title: 'Lego Harry Potter : Années 5 à 7', url: 'games/lego-harry-potter-annees-5-a-7.html' },
      { title: 'As Dusk Falls', url: 'games/as-dusk-falls.html' },
      { title: 'Aska', url: 'games/aska.html' },
      { title: 'Batman : The Enemy Within', url: 'games/batman-the-enemy-within.html' },
      { title: 'Batman : The Telltale Series', url: 'games/batman-the-telltale-series.html' },
      { title: 'Black Myth : Wukong', url: 'games/black-myth-wukong.html' },
      { title: 'Blue Prince', url: 'games/blue-prince.html' },
      { title: 'Clair Obscur : Expedition 33', url: 'games/clair-obscur-expedition-33.html' },
      { title: 'Corepunk', url: 'games/corepunk.html' },
      { title: 'Cyberpunk 2077', url: 'games/cyberpunk-2077.html' },
      { title: 'Dead Island 2', url: 'games/dead-island-2.html' },
      { title: 'Detroit : Become Human', url: 'games/detroit-become-human.html' },
      { title: 'Devil May Cry 5', url: 'games/devil-may-cry-5.html' },
      { title: "Dragon's Dogma 2", url: 'games/dragons-dogma-2.html' },
      { title: 'Dying Light 2', url: 'games/dying-light-2.html' },
      { title: 'Elden Ring : Shadow of the Erdtree', url: 'games/elden-ring-shadow-of-the-erdtree.html' },
      { title: 'Enotria : The Last Song', url: 'games/enotria-the-last-song.html' },
      { title: 'Enshrouded', url: 'games/enshrouded.html' },
      { title: 'Fantasy Life i : La voleuse de temps', url: 'games/fantasy-life-i-la-voleuse-de-temps.html' },
      { title: 'Final Fantasy', url: 'games/final-fantasy.html' },
      { title: 'Final Fantasy VII : Crisis Core Remastered', url: 'games/final-fantasy-vii-crisis-core-remastered.html' },
      { title: 'Final Fantasy VII : Remake', url: 'games/final-fantasy-vii-remake.html' },
      { title: 'Final Fantasy VII : Rebirth', url: 'games/final-fantasy-vii-rebirth.html' },
      { title: 'Final Fantasy XVI', url: 'games/final-fantasy-xvi.html' },
      { title: 'God of War 4', url: 'games/god-of-war-4.html' },
      { title: 'God of War 5 : Ragnarok', url: 'games/god-of-war-5-ragnarok.html' },
      { title: 'Gotham Knights', url: 'games/gotham-knights.html' },
      { title: 'Harry Potter et la chambre des secrets (Game Cube)', url: 'games/harry-potter-et-la-chambre-des-secrets-game-cube.html' },
      { title: 'Kingdom Come : Deliverance 2', url: 'games/kingdom-come-deliverance-2.html' },
      { title: "La Terre du Milieu : L'ombre de la Guerre", url: 'games/la-terre-du-milieu-l-ombre-de-la-guerre.html' },
      { title: 'Life is Strange', url: 'games/life-is-strange.html' },
      { title: 'Life is Strange 2', url: 'games/life-is-strange-2.html' },
      { title: 'Life is Strange : Before the Storm', url: 'games/life-is-strange-before-the-storm.html' },
      { title: 'Life is Strange : True Colors', url: 'games/life-is-strange-true-colors.html' },
      { title: 'Little Nightmares', url: 'games/little-nightmares.html' },
      { title: 'Little Nightmares 2', url: 'games/little-nightmares-2.html' },
      { title: "Marvel's Avengers", url: 'games/marvel-s-avengers.html' },
      { title: "Marvel's Spider-Man", url: 'games/marvel-s-spider-man.html' },
      { title: "Marvel's Spider-Man 2", url: 'games/marvel-s-spider-man-2.html' },
      { title: "Marvel's Spider-Man : Miles Morales", url: 'games/marvel-s-spider-man-miles-morales.html' },
      { title: 'My Friend Pedro', url: 'games/my-friend-pedro.html' },
      { title: 'Nier Automata', url: 'games/nier-automata.html' },
      { title: 'Palworld', url: 'games/palworld.html' },
      { title: 'Pokémon Saphir Alpha', url: 'games/pokemon-saphir-alpha.html' },
      { title: 'Pokémon Écarlate', url: 'games/pokemon-ecarlate.html' },
      { title: 'Légendes Pokémon : Arceus', url: 'games/legendes-pokemon-arceus.html' },
      { title: 'Pokémon Épée', url: 'games/pokemon-epee.html' },
      { title: 'Remember Me', url: 'games/remember-me.html' },
      { title: 'Rise of the Ronin', url: 'games/rise-of-the-ronin.html' },
      { title: 'Road 96', url: 'games/road-96.html' },
      { title: 'Road 96 : Mile 0', url: 'games/road-96-mile-0.html' },
      { title: 'Soulmask', url: 'games/soulmask.html' },
      { title: 'Star Wars : Jedi Fallen Order', url: 'games/star-wars-jedi-fallen-order.html' },
      { title: 'Star Wars : Jedi Survivor', url: 'games/star-wars-jedi-survivor.html' },
      { title: 'Star Wars : Outlaws', url: 'games/star-wars-outlaws.html' },
      { title: 'Suicide Squad : Kill the Justice League', url: 'games/suicide-squad-kill-the-justice-league.html' },
      { title: 'Tales of Arise', url: 'games/tales-of-arise.html' },
      { title: 'Tekken 8', url: 'games/tekken-8.html' },
      { title: 'The First Berserker : Khazan', url: 'games/the-first-berserker-khazan.html' },
      { title: 'The Last of US', url: 'games/the-last-of-us.html' },
      { title: 'The Walking Dead', url: 'games/the-walking-dead.html' },
      { title: 'The Walking Dead : Saison 2', url: 'games/the-walking-dead-saison-2.html' },
      { title: 'Tomb Raider (2013)', url: 'games/tomb-raider-2013.html' },
      { title: 'Rise of the Tomb Raider', url: 'games/rise-of-the-tomb-raider.html' },
      { title: 'Shadow of the Tomb Raider', url: 'games/shadow-of-the-tomb-raider.html' },
      { title: 'Valheim', url: 'games/valheim.html' },
      { title: 'Wartales', url: 'games/wartales.html' },
      { title: 'The Wolf Among Us', url: 'games/the-wolf-among-us.html' },
      { title: 'Wo Long : Fallen Dynasty', url: 'games/wo-long-fallen-dynasty.html' },
      { title: 'Yakuza : Like a Dragon', url: 'games/yakuza-like-a-dragon.html' },
      { title: 'The Outer Worlds', url: 'games/the-outer-worlds.html' },
      { title: 'FALLOUT 4', url: 'games/fallout-4.html' },
      { title: 'Sonic Adventure 2 Battle (Game Cube)', url: 'games/sonic-adventure-2-battle.html' },
      { title: 'Lies of P : Overture', url: 'games/lies-of-p-overture.html' },
      { title: 'Batman : Arkham City', url: 'games/batman-arkham-city.html' },
      { title: 'Ori and the Blind Forest', url: 'games/ori-and-the-blind-forest.html' },
      { title: "SOUTH PARK : L'Annale du Destin", url: 'games/south-park-l-annale-du-destin.html' },
      { title: 'SOUTH PARK : Le Baton de la Vérité', url: 'games/south-park-le-baton-de-la-verite.html' },
      { title: 'Batman : Arkham Origins', url: 'games/batman-arkham-origins.html' },
      { title: "La Terre du Milieu : L'Ombre du Mordor", url: 'games/la-terre-du-milieu-l-ombre-du-mordor.html' },
      { title: 'Animal Crossing : New Horizons', url: 'games/animal-crossing-new-horizons.html' },
      { title: 'Final Fantasy XV', url: 'games/final-fantasy-xv.html' },
      { title: 'It Takes Two', url: 'games/it-takes-two.html' },
      { title: "Baldur's Gate III", url: 'games/baldur-s-gate-iii.html' },
      { title: 'Borderlands 4', url: null },
      { title: 'Dying Light : The Beast', url: 'games/dying-light-the-beast.html' },
      { title: 'MegaBonk', url: 'games/megabonk.html' },
      { title: 'Sonic Racing : CrossWorlds', url: 'games/sonic-racing-crossworlds.html' },
      { title: 'Dying Light', url: 'games/dying-light.html' },
      { title: 'Légendes Pokémon : Z-A', url: 'games/legendes-pokemon-z-a.html' },
      { title: 'Ghost of Yotei', url: 'games/ghost-of-yotei.html' },
      { title: 'Dragon Ball Gekishin Squadra', url: null },
      { title: 'Dragon Ball Z : Dokkan Battle', url: null },
      { title: 'Might and Magic : Elemental Guardians', url: null },
      { title: 'Epic Seven', url: null },
      { title: 'Summoners War : Sky Arena', url: null },
      { title: 'Dragon Ball Legends', url: null },
      { title: 'Genshin Impact', url: null },
      { title: 'Etheria : Restart', url: null },
      { title: 'Persona 5 : The Phantom X', url: null },
      { title: 'Blue Protocol : Star Resonance', url: 'games/blue-protocol-star-resonance.html' },
      { title: 'Destiny : Rising', url: null },
      { title: 'Wuthering Waves', url: 'games/wuthering-waves.html' },
      { title: 'Tower of Fantasy', url: null },
      { title: 'Seven Deadly Sins : Grand Cross', url: null },
      { title: 'Seven Deadly Sins : Origins', url: null },
      { title: 'Rememento : White Shadow', url: null },
      { title: 'DC Legends', url: null },
      { title: 'DC Worlds Collide', url: null },
      { title: 'DC : Dark legion', url: null },
      { title: 'DC Heroes and Vilains', url: null },
      { title: 'Watcher of Realms', url: null },
      { title: 'Raid : Shadow Legends', url: null },
      { title: 'Tribe Nine', url: null },
      { title: 'Summoners War : Chronicles', url: null },
      { title: 'Honkai Star Rail', url: null },
      { title: 'Zenless Zone Zero', url: null },
      { title: 'Black Clover M', url: null },
      { title: 'Final Fantasy VII : Ever Crisis', url: null },
      { title: 'War Of The Visions : Final Fantasy Brave Exvius', url: null },
      { title: 'Solo Leveling : Arise', url: null },
      { title: 'King Arthur : Legends Rise', url: null },
      { title: 'Chaos Zero Nightmare', url: null },
      { title: 'Dislyte', url: null },
      { title: 'Sword Of Convallaria', url: null },
      { title: 'Dissidia Final Fantasy Opera Omnia', url: null },
      { title: 'Exos Heroes', url: null },
      { title: 'Mobius Final Fantasy', url: null },
      { title: 'Jujutsu Kaisen Phantom Parade', url: null },
      { title: 'Harry Potter : Magic Awakened', url: null },
      { title: 'Astra : Knights Of veda', url: 'games/astra-knights-of-veda.html' },
      { title: 'Code Vein', url: null },
      { title: 'Code Vein 2', url: null },
      { title: 'Duet Night Abyss', url: 'games/duet-night-abyss.html' },
      { title: 'Dispatch', url: 'games/dispatch.html' },
      


  
];
